### ISSUE TITLE
Preparing at least two more examples with their outputs until the Friday seminar

### ISSUE THREAD

**Issue by mahdifani14** [mahdifani14/AutoTuning#5]
Let's get some new experimental result until the Friday seminar in which we are going to attend.

**Comment by pooyaww** [comment]
@mahdifani14 Tomorrow we are going to attend in ComoNext to get some more information regarding Neatech.. I hope to find the time to modify the codes for HW synthesis.

**Comment by mahdifani14** [comment]
@pooyaww I have annotated another two codes that one of them (mat3x3) has been executed with Orio and is ready for testing with Leg-Up. Please pull the master branch and check the recent changes.
